pid /home/app/.config/bizshuk.github.io/data/nginx.pid;

events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

server {
    listen 8306;
    listen [::]:8306;
    server_name _;
    root /home/app/out/html;

    location / {
        try_files $uri $uri/ $uri.html =404;
    }
}
}
